### ISSUE TITLE
I found out how to not use eval.

### ISSUE THREAD

**Issue by FreezePhoenix** [NexusNull/ALBot#17]
In the end, I noticed that various functions are not showing up due to lack of them being on the parent object. However, many of these functions are defined in various phases of the code. In the end, I believe you should use `vm`, a native nodejs module that allows you to execute code in a specific context. You can then make this context be the parent. and then run the CODE file in a separate context that has that as .parent

**Comment by NexusNull** [comment]
Bight me worth investigating but for now there are more important issues at hand.

**Comment by FreezePhoenix** [comment]
Will research.

**Comment by FreezePhoenix** [comment]
Ey if you could give me some examples of what is more important I can try and look at them. I'm currently doing meh RN i need something to do.

**Comment by Box-Bop** [comment]
@FreezePhoenix One issue is how the map doesn't get initialized properly. My CODE has my bot walk away from a target as it approaches the character, reaching a wall has a high chance of the server sending my bot to jail.

**Comment by FreezePhoenix** [comment]
@Box-Bop 🤔 that is an issue I have experienced, and it does happen often, and while it is annoying, I laugh at the "Jesus" moments where you walk across the water. That is interesting though.

**Comment by FreezePhoenix** [comment]
@Box-Bop A temporary solution (until Wiz makes checks be mandated) would be to comment out the "debug position"

alternatively, you can also manually detect when you are in the jail.

```js
setInterval(() => {
   if(character.map == "jail") {
      parent.socket.emit("leave");
   }
}, 500)
```

Disclaimer: I may or may not use one or more of the above techniques,  and I am not responsible for disciplinary action resulting from these techniques.
