### ISSUE TITLE
Cannot figure out how to call switchServer func

### ISSUE THREAD

**Issue by wofka72** [NexusNull/ALBot#53]
Cannot figure out how to call `switchServer` function from `./app/Extensions.js` while inside my own character's code. I tried to see from the files what the hierarchy does objects have and tried this code:
`game.process.gameContext.context.albot.switchServer`. But object `game` have no `process` field so it failed.
Could someone share working code?

**Comment by NexusNull** [comment]
Oh sorry, I didn't get notified about issues, I'll look into this.

**Comment by NexusNull** [comment]
`parent.albot.switchServer("EU I")`
